---
title: "Fig1"
output: html_document
date: "2025-09-30"
---
#alpha_diversity_flow_TPA_wilcox
library(vegan)
library(agricolae)
library(ggplot2)
library(ggpubr)
args=commandArgs(TRUE)
inf1=args[1]
inf2=args[2]
outf=args[3]
outf_pdf1=args[4]
outf_pdf2=args[5]

otu=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=7)
otu=otu[,8:ncol(otu)]
otu=as.data.frame(t(otu))
#-------------------
shannon=diversity(otu,"shannon")
simpson=diversity(otu,"simpson")
alpha=data.frame(shannon,simpson)
#-------------------------------
data_phe=read.table(inf2,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F)
colnames(data_phe)<-c("Name","group")
alpha$Name=rownames(alpha)
m=merge(alpha,data_phe,by="Name",all=T)
alpha<-m
write.table(alpha,outf,sep="\t",quote=F,col.names=T,row.names=F)

mycompare=list(c('T','A'),c('T','P'),c('A','P'))
p=ggboxplot(alpha,x="group",y="shannon",color="black",add="jitter",add.params = list(color = "black",fill="group",shape="group"),palette = c("aaas"),fill="group")+stat_compare_means(comparisons=mycompare,label = "p.format",method = 'wilcox',p.adjust.methods="fdr")  +
  stat_compare_means(method = "kruskal.test", 
                     label = "p.format", 
                     label.y = max(alpha$shannon, na.rm = TRUE) * 1.1,color="red")  # 添加全局检验#alpha是一个行名是样本的数据,lable="p.format"显示p值
ggsave(plot=p,outf_pdf1,height = 7,width = 6,dpi = 300)
p=ggboxplot(alpha,x="group",y="simpson",color="black",add="jitter",add.params = list(color = "black",fill="group",shape="group"),palette = c("aaas"),fill="group")+stat_compare_means(comparisons=mycompare,label = "p.format",method = 'wilcox',p.adjust.methods="fdr") +
  stat_compare_means(method = "kruskal.test", 
                     label = "p.format", 
                     label.y = max(alpha$simpson, na.rm = TRUE) * 1.1,color="red")  # 添加全局检验#alpha是一个行名是样本的数据
ggsave(plot=p,outf_pdf2,height = 7,width = 6,dpi = 300)
#alpha_diversity_flow_stage
library(vegan)
library(agricolae)
library(ggplot2)
library(ggpubr)
args=commandArgs(TRUE)
inf1=args[1]
inf2=args[2]
outf=args[3]
outf_pdf1=args[4]
outf_pdf2=args[5]


otu=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=7)
otu=as.data.frame(t(otu))
row_A=grep("A",rownames(otu),value=T)
otu_A=otu[as.vector(row_A),]
row_T=grep("T",rownames(otu),value=T)
otu_T=otu[as.vector(row_T),]
otu1=rbind(otu_A,otu_T)
otu=otu1
otu<-sapply(otu,as.numeric)
rownames(otu)<-rownames(otu1)
shannon=diversity(otu,"shannon")
simpson=diversity(otu,"simpson")
alpha=data.frame(shannon,simpson)
data_phe=read.table(inf2,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F)
colnames(data_phe)<-c("Name","group")
alpha$Name=rownames(alpha)
m=merge(alpha,data_phe,by="Name",all=T)
alpha<-m
write.table(alpha,outf,sep="\t",quote=F,col.names=T,row.names=F)

mycompare_stage=list(c('Early_stage','A'),c('Early_stage','Advanced_stage'),c('A','Advanced_stage'))
p=ggboxplot(alpha,x="group",y="shannon",color="black",add="jitter",add.params = list(color = "black",fill="group",shape="group"),palette = c("aaas"),fill="group")+stat_compare_means(comparisons=mycompare_stage,label = "p.format",method = 'wilcox',p.adjust.methods="fdr")  +
  stat_compare_means(method = "kruskal.test", 
                     label = "p.format", 
                     label.y = max(alpha$shannon, na.rm = TRUE) * 1.1,color="red")  # 添加全局检验
ggsave(plot=p,outf_pdf1,height = 7,width = 6,dpi = 300)
p=ggboxplot(alpha,x="group",y="simpson",color="black",add="jitter",add.params = list(color = "black",fill="group",shape="group"),palette = c("aaas"),fill="group")+stat_compare_means(comparisons=mycompare_stage,label = "p.format",method = 'wilcox',p.adjust.methods="fdr") +
  stat_compare_means(method = "kruskal.test", 
                     label = "p.format", 
                     label.y = max(alpha$simpson, na.rm = TRUE) * 1.1,color="red")  # 添加全局检验
ggsave(plot=p,outf_pdf2,height = 7,width = 6,dpi = 300)

#beta_diversity_TPA
library(ecodist) 
library(vegan) 
library(ggplot2)
library(ggpubr)
library(pairwiseAdonis) 
library(patchwork)
args=commandArgs(TRUE)
inf1=args[1]
inf2=args[2]
outf_pdf=args[3]
spe=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=7)
spe=spe[,8:ncol(spe)]
spe=as.data.frame(t(spe))
data_phe=read.table(inf2,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F)
spe=spe[!apply(spe[,],1,sum)==0,]

colnames(data_phe)<-c("Name","group")
spe.dist<-vegdist(spe,) 
d=as.matrix(spe.dist)
data_phe1=as.data.frame(data_phe[,-1])
rownames(data_phe1) <-data_phe[,1]
colnames(data_phe1) <-"group"

data_phe2=as.data.frame(data_phe1[as.vector(rownames(spe)),])
rownames(data_phe2)=rownames(spe)
colnames(data_phe2) <-"group"
data_phe2$Name=rownames(data_phe2)
data_phe3<-data_phe2[order(data_phe2[,1]),]
data_phe4=as.data.frame(data_phe3[,1])
rownames(data_phe4)<-rownames(data_phe3)
colnames(data_phe4)<-"group"
data_phe2=data_phe4

bray=adonis2(spe ~ group,data=data_phe2,permutations=999,method="bray") 
label_p=paste("p=",bray$Pr[1])

pairwise_bray=pairwise.adonis(x=spe,factors=data_phe2$group,sim.function="vegdist",sim.method="bray",p.adjust.m="BH",reduce=NULL,perm=999)
pcoa = cmdscale(d, k=3, eig=T)
points = as.data.frame(pcoa$points)
colnames(points) = c("x", "y", "z")
points$Name=rownames(points)
m=merge(points,data_phe,by="Name")
points=m[,-1]
colnames(points)[4]<-"group" 
eig = pcoa$eig 
p = ggplot(points, aes(x=x, y=y, color=group, shape=group)) +
  geom_point(alpha=.7, size=2) +
  stat_ellipse(level=0.95,size=1,linetype=5) + 
  labs(x=paste("PCoA 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
       y=paste("PCoA 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep=""),
       title="bray_curtis PCoA") +
  theme(panel.background = element_rect(fill='white',colour = 'black'),axis.title.x=element_text(colour = 'black',size=15),axis.title.y = element_text(colour = 'black',size=15),legend.text = element_text(size = 15)) +
  annotate("text",x=-0.35,y=-0.35,parse=TRUE,size=5,label=label_p,family="Times",fontface="italic",color="black")+  
  scale_color_manual(values=c("#00FFFF","#00FF7F","#FFFF00")) 
tab2 <- ggtexttable(pairwise_bray[,c("pairs","p.value")], rows = NULL,
                    theme = ttheme("blank")) %>%
  tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 1)  %>%
  tab_add_hline(at.row = nrow(pairwise_bray)+1, row.side = "bottom", linewidth = 1)

p2=p+tab2
p2

ggsave(outf_pdf, p2, width = 7, height = 5) 

#beta_diversity_flow_stage
library(ecodist) 
library(vegan)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(pairwiseAdonis) 
args=commandArgs(TRUE)
inf1=args[1]
inf2=args[2]
outf_pdf=args[3]
spe=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=7)
spe=spe[,8:ncol(spe)]
spe=as.data.frame(t(spe))
row_A=grep("A",rownames(spe),value=T)
otu_A=spe[as.vector(row_A),]
row_T=grep("T",rownames(spe),value=T)
otu_T=spe[as.vector(row_T),]
otu1=rbind(otu_A,otu_T)
spe=otu1
spe=spe[!apply(spe[,],1,sum)==0,]

data_phe=read.table(inf2,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F)
colnames(data_phe)<-c("Name","group")
spe.dist<-vegdist(spe,) 
d=as.matrix(spe.dist)
data_phe1=as.data.frame(data_phe[,-1])
rownames(data_phe1) <-data_phe[,1]
colnames(data_phe1) <-"group"

data_phe2=as.data.frame(data_phe1[as.vector(rownames(spe)),])
rownames(data_phe2)=rownames(spe)
colnames(data_phe2) <-"group"
data_phe2$Name=rownames(data_phe2)
'''data_phe3<-data_phe2[order(data_phe2[,1]),]
data_phe4=as.data.frame(data_phe3[,1])
rownames(data_phe4)<-rownames(data_phe3)
colnames(data_phe4)<-"group"
data_phe2=data_phe4
'''
pheA<-data_phe2[data_phe2[,1]=="A",]
pheE<-data_phe2[data_phe2[,1]=="Early_stage",]
pheL<-data_phe2[data_phe2[,1]=="Advanced_stage",]
m3=rbind(pheA,pheE,pheL)
m4=as.data.frame(m3[,-2])
row.names(m4)<-rownames(m3)
colnames(m4)="group"
data_phe2=m4

bray=adonis2(spe ~ group,data=data_phe2,permutations=999,method="bray") 
label_p=paste("p=",bray$Pr[1])
pairwise_bray=pairwise.adonis(x=spe,factors=data_phe2$group,sim.function="vegdist",sim.method="bray",p.adjust.m="BH",reduce=NULL,perm=999) 

pcoa = cmdscale(d, k=3, eig=T) 
points = as.data.frame(pcoa$points)
colnames(points) = c("x", "y", "z")
points$Name=rownames(points)
m=merge(points,data_phe,by="Name")
points=m[,-1]
colnames(points)[4]<-"group" 
eig = pcoa$eig 
p1=rbind(points[points[,4]=="A",],points[points[,4]=="Early_stage",],points[points[,4]=="Advanced_stage",]) 
points=p1

p = ggplot(points, aes(x=x, y=y, color=group, shape=group)) +
  geom_point(alpha=.7, size=2) +
  stat_ellipse(level=0.95,size=1,linetype=5) + 
  labs(x=paste("PCoA 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""), 
       y=paste("PCoA 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep=""),
       title="bray_curtis PCoA") +
  theme(axis.ticks=element_line(size=1,color="black"),panel.background = element_rect(fill='white',colour = 'black'),axis.title.x=element_text(colour = 'black',size=15),axis.title.y = element_text(colour = 'black',size=15),legend.text = element_text(size = 15) ,panel.grid = element_blank()) +
  annotate("text",x=-0.4,y=-0.5,parse=TRUE,size=5,label=label_p,family="Times",fontface="italic",color="black")+
  scale_color_manual(values=c("A"="#00FFFF","Early_stage"="#FFB5C5","Advanced_stage"="#FF4500"),breaks=c("A", "Early_stage", "Advanced_stage"))
  
p
p1=p+ guides(shape="none") 
p1


tab2 <- ggtexttable(pairwise_bray[,c("pairs","p.value")], rows = NULL, #add p-value between groups
                    theme = ttheme("blank")) %>%
  tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 1)  %>%
  tab_add_hline(at.row = nrow(pairwise_bray)+1, row.side = "bottom", linewidth = 1)

p2=p1+tab2
p2
ggsave(outf_pdf, p2, width = 12, height = 5)
