---
title: "Fig7"
output: html_document
date: "2025-10-01"
---

#pheatmap
library(pheatmap)
inf1="pheatmap_merge_T_input_wardD2.tsv"  #inf1是输入文件，不同分组用不同的输入文件

data=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=1)
data=as.data.frame(t(data))
bk <- unique(c(seq(-4,4, length=100)))
aa<-pheatmap(as.matrix(data),breaks=bk,cluster_rows=F,cluster_cols=F,treeheight_col=50,color=colorRampPalette(c("#010108","#1D1048","#4F137B","#812381","#B3357A","#E65263","#FD8A62","#FDC78B","#FBFBBC"))(100),fontsize_row=7,fontsize_col=7,border=FALSE)

#RM
```{r}
################################################################################################
# install.packages("")

library(caret)
library(pROC)
library(ggplot2)
library(pheatmap)
library(openxlsx)
library(dplyr)
################################################################################################
# 函数
# 样本计数函数
num_not_zero <- function(data) {
  data[data==0] <- NA
  data <- t(data)
  data_0 <- colSums(is.na(data))
  data_0 <- nrow(data)-data_0
  data_table <- data.frame(data_0)
  return(data_table)
}
# 分类计数函数
num <- function(data,type){
  n <- 0
  for(i in 1:nrow(data)) {
    if((data$type[i]==type)){
      n <- n+1
    }
  }
  return(n)
}
# 将数目列表按每类别分开,卡数量
segment_num <- function(data,type,n){
  x <- c()
  j = 1
  for(i in 1:nrow(data)) {
    if((data$type[i]==type&&data$n[i]>=n)){
      x[j] <- i
      j <- j+1
    }
  }
  return(data[x,])
}
# 参考分开后的数目列表将数据列表按每类别分开
segment_data <- function(data1,data2){
  x <- c()
  for(i in 1:nrow(data2)) {
    for(j in 1:nrow(data1)){
      if(data2[i,1]==row.names(data1)[j]){
        x[i]=j
      }
    }
  }
  return(data1[x,])
}
# 交叉验证
rfcv_auc <- function(data){
  y = numeric(0)
  prob = numeric(0)
  pred = numeric(0)
  set.seed(1234)
  folds <- createFolds(data$type, k=5, returnTrain = TRUE)
  for (i in 1:5) {
    train_data <- data[folds[[i]],]
    test_data <- data[-folds[[i]],]
    train_data$type = factor(train_data$type,levels = c("A","T"))
    test_data$type = factor(test_data$type,levels = c("A","T"))
    set.seed(1234)
    rf_model <- randomForest(type~., data=train_data, ntree=1000, importance=TRUE,proximity=TRUE)
    fitted.prob <- predict(rf_model, test_data,type = "prob")
    predictions <- predict(rf_model, test_data)
    y = c(y, test_data$type)
    prob = c(prob, fitted.prob[,1])
    pred = c(pred, predictions)
  }
  return(list(label = y, prob = prob, pred = pred))
}
# 获取索引
topgini_index <- function(imp,table,n){
  names <- row.names(imp)
  t <- c()
  table <- data.frame(t(table))
  for(j in 1:n){
    for(i in 1:nrow(table)) {
      if(row.names(table)[i]==names[j]){
        t[j] = i
      }
    }
  }
  return(t)
}
# gini重要度变化值
gini_change <- function(table,index) {
  auc <- c()
  acc <- c()
  type = data.frame(table$type)
  table <- t(table)
  for(i in 1:length(index)){
    table_1 <- data.frame(table[index[1:i],])
    if(nrow(table_1)<ncol(table_1)){
      table_1 <- t(table_1)
    }
    table_1 <- cbind(table_1,type)
    colnames(table_1)[i+1] <- "type"
    table_1$type = factor(table_1$type,levels = c("A","T"))
    model <- rfcv_auc(table_1)
    roc_prob <- roc(model$label,model$prob,ci=T)
    auc[i] <- roc_prob$auc
    confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
    acc[i] <- confusion_matrix$overall[1]
  }
  return(list(auc = auc, acc = acc))
}
# gini重要度变化折线图
change_plot <- function(change) {
  y = data.frame(change)
  y$x = c(1:nrow(y))
  ggplot(data = y) +
    geom_line(aes(x = x, y = auc, color = "AUC")) +
    geom_line(aes(x = x, y = acc, color = "ACC")) +
    labs(x = "num of maker", y = "value", title = "AUCandACC change") +
    scale_color_manual(values = c("AUC" = "blue", "ACC" = "red")) +
    theme_minimal()
}
################################################################################################
# A_T_taxon
# 读入原始数据
# setwd("../../../")
# D种类S物种名,263个菌
A_taxon_data <- read.csv('diff_AT_A.txt', sep = "\t")
T_taxon_data <- read.csv('diff_AT_T.txt', sep = "\t")
# 名称和种类
A_taxon_data_type <- A_taxon_data[,1:2]
T_taxon_data_type <- T_taxon_data[,1:2]
# 全数据表格
row.names(A_taxon_data) <- A_taxon_data[,2]
row.names(T_taxon_data) <- T_taxon_data[,2]
A_taxon_data <- A_taxon_data[,-c(1,2)]
T_taxon_data <- T_taxon_data[,-c(1,2)]
# 每个菌的数量
A_taxon_num <- num_not_zero(A_taxon_data)
T_taxon_num <- num_not_zero(T_taxon_data)
# 合并成一个数目列表
AT_taxon_num <- data.frame(row.names(A_taxon_data))
AT_taxon_num$A <- A_taxon_num$data_0
AT_taxon_num$T <- T_taxon_num$data_0
AT_taxon_num$n <- AT_taxon_num$A+AT_taxon_num$T
# 加上标志物分类
AT_taxon_num$type <- A_taxon_data_type$D
# 四类标准物Bacteria,Archaea,Fungi,Viruses的数目
AT_n_Bacteria <- num(AT_taxon_num,"Bacteria")
AT_n_Fungi <- num(AT_taxon_num,"Fungi")
AT_n_Archaea <- num(AT_taxon_num,"Archaea")
AT_n_Viruses <- num(AT_taxon_num,"Viruses")
# 对数目列表切分
# 卡一下recurrence,输入参数n,先卡一个大于等于20
AT_taxon_num_Bacteria <- segment_num(AT_taxon_num,"Bacteria",20)
AT_taxon_num_Fungi <- segment_num(AT_taxon_num,"Fungi",20)
AT_taxon_num_Archaea <- segment_num(AT_taxon_num,"Archaea",20)
AT_taxon_num_Viruses <- segment_num(AT_taxon_num,"Viruses",20)
# 对数据列表切分
A_taxon_data_Bacteria <- segment_data(A_taxon_data,AT_taxon_num_Bacteria)
T_taxon_data_Bacteria <- segment_data(T_taxon_data,AT_taxon_num_Bacteria)
A_taxon_data_Fungi <- segment_data(A_taxon_data,AT_taxon_num_Fungi)
T_taxon_data_Fungi <- segment_data(T_taxon_data,AT_taxon_num_Fungi)
A_taxon_data_Archaea <- segment_data(A_taxon_data,AT_taxon_num_Archaea)
T_taxon_data_Archaea <- segment_data(T_taxon_data,AT_taxon_num_Archaea)
A_taxon_data_Viruses <- segment_data(A_taxon_data,AT_taxon_num_Viruses)
T_taxon_data_Viruses <- segment_data(T_taxon_data,AT_taxon_num_Viruses)
############################################################
# Bacteria
A_taxon_table_Bacteria <- data.frame(t(A_taxon_data_Bacteria))
A_taxon_table_Bacteria$type <- "A"
T_taxon_table_Bacteria <- data.frame(t(T_taxon_data_Bacteria))
T_taxon_table_Bacteria$type <- "T"
AT_taxon_table_Bacteria <- rbind(A_taxon_table_Bacteria,T_taxon_table_Bacteria)
# 随机森林
model <- rfcv_auc(AT_taxon_table_Bacteria)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.8790323 
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.9386
# 找到最小集合
AT_taxon_table_Bacteria$type = factor(AT_taxon_table_Bacteria$type,levels = c("A","T"))
set.seed(1234)
AT_rf_model_Bacteria <- randomForest(type~., data=AT_taxon_table_Bacteria, ntree=1000, importance=TRUE,proximity=TRUE)
impAT_Bacteria = as.data.frame(AT_rf_model_Bacteria$importance)
impAT_Bacteria = dplyr::arrange(impAT_Bacteria,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
AT_index_Bacteria = topgini_index(impAT_Bacteria,AT_taxon_table_Bacteria,20)
AT_change_Bacteria = gini_change(AT_taxon_table_Bacteria,AT_index_Bacteria)
change_plot(AT_change_Bacteria)
A_final_B <- A_taxon_data_Bacteria[AT_index_Bacteria[1:8],]
T_final_B <- T_taxon_data_Bacteria[AT_index_Bacteria[1:8],]
############################################################
############################################################
# Archaea
A_taxon_table_Archaea <- data.frame(t(A_taxon_data_Archaea))
A_taxon_table_Archaea$type <- "A"
T_taxon_table_Archaea <- data.frame(t(T_taxon_data_Archaea))
T_taxon_table_Archaea$type <- "T"
AT_taxon_table_Archaea <- rbind(A_taxon_table_Archaea,T_taxon_table_Archaea)
# 随机森林
model <- rfcv_auc(AT_taxon_table_Archaea)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.7419355  
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.7832
# 找到最小集合
AT_taxon_table_Archaea$type = factor(AT_taxon_table_Archaea$type,levels = c("A","T"))
set.seed(1234)
AT_rf_model_Archaea <- randomForest(type~., data=AT_taxon_table_Archaea, ntree=1000, importance=TRUE,proximity=TRUE)
impAT_Archaea = as.data.frame(AT_rf_model_Archaea$importance)
impAT_Archaea = dplyr::arrange(impAT_Archaea,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
AT_index_Archaea = topgini_index(impAT_Archaea,AT_taxon_table_Archaea,5)
AT_change_Archaea = gini_change(AT_taxon_table_Archaea,AT_index_Archaea)
change_plot(AT_change_Archaea)
A_final_A <- A_taxon_data_Archaea[AT_index_Archaea[1:2],]
T_final_A <- T_taxon_data_Archaea[AT_index_Archaea[1:2],]
############################################################
# Fungi
A_taxon_table_Fungi <- data.frame(t(A_taxon_data_Fungi))
A_taxon_table_Fungi$type <- "A"
T_taxon_table_Fungi <- data.frame(t(T_taxon_data_Fungi))
T_taxon_table_Fungi$type <- "T"
AT_taxon_table_Fungi <- rbind(A_taxon_table_Fungi,T_taxon_table_Fungi)
# 随机森林
model <- rfcv_auc(AT_taxon_table_Fungi)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.733871
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.798
# 找到最小集合
AT_taxon_table_Fungi$type = factor(AT_taxon_table_Fungi$type,levels = c("A","T"))
set.seed(1234)
AT_rf_model_Fungi <- randomForest(type~., data=AT_taxon_table_Fungi, ntree=1000, importance=TRUE,proximity=TRUE)
impAT_Fungi = as.data.frame(AT_rf_model_Fungi$importance)
impAT_Fungi = dplyr::arrange(impAT_Fungi,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
AT_index_Fungi = topgini_index(impAT_Fungi,AT_taxon_table_Fungi,4)
AT_change_Fungi = gini_change(AT_taxon_table_Fungi,AT_index_Fungi)
change_plot(AT_change_Fungi)
A_final_F <- A_taxon_data_Fungi[AT_index_Fungi[1:3],]
T_final_F <- T_taxon_data_Fungi[AT_index_Fungi[1:3],]
############################################################
# Viruses
A_taxon_table_Viruses <- data.frame(t(A_taxon_data_Viruses))
A_taxon_table_Viruses$type <- "A"
T_taxon_table_Viruses <- data.frame(t(T_taxon_data_Viruses))
T_taxon_table_Viruses$type <- "T"
AT_taxon_table_Viruses <- rbind(A_taxon_table_Viruses,T_taxon_table_Viruses)
# 随机森林
model <- rfcv_auc(AT_taxon_table_Viruses)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.6370968
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.7149
# 找到最小集合
AT_taxon_table_Viruses$type = factor(AT_taxon_table_Viruses$type,levels = c("A","T"))
set.seed(1234)
AT_rf_model_Viruses <- randomForest(type~., data=AT_taxon_table_Viruses, ntree=1000, importance=TRUE,proximity=TRUE)
impAT_Viruses = as.data.frame(AT_rf_model_Viruses$importance)
impAT_Viruses = dplyr::arrange(impAT_Viruses,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
AT_index_Viruses = topgini_index(impAT_Viruses,AT_taxon_table_Viruses,5)
AT_change_Viruses = gini_change(AT_taxon_table_Viruses,AT_index_Viruses)
change_plot(AT_change_Viruses)
A_final_V <- A_taxon_data_Viruses[AT_index_Viruses[1:1],]
T_final_V <- T_taxon_data_Viruses[AT_index_Viruses[1:1],]
############################################################
################################################################################################
# 热图
t <- c()
for(i in 1:2){
  for(j in 1:5){
    if(row.names(A_taxon_data_Archaea)[j]==row.names(A_final_A)[i]){
      t[i] = j
    }
  }
}
TTT_A0 <- AT_taxon_num_Archaea[t,]
t <- c()
for(i in 1:8){
  for(j in 1:230){
    if(row.names(A_taxon_data_Bacteria)[j]==row.names(A_final_B)[i]){
      t[i] = j
    }
  }
}
TTT_B0 <- AT_taxon_num_Bacteria[t,]
t <- c()
for(i in 1:3){
  for(j in 1:4){
    if(row.names(A_taxon_data_Fungi)[j]==row.names(A_final_F)[i]){
      t[i] = j
    }
  }
}
TTT_F0 <- AT_taxon_num_Fungi[t,]
t <- c()
for(i in 1:1){
  for(j in 1:5){
    if(row.names(A_taxon_data_Viruses)[j]==row.names(A_final_V)[i]){
      t[i] = j
    }
  }
}
TTT_V0 <- AT_taxon_num_Viruses[t,]

TTT_19 = rbind(TTT_A0,TTT_B0,TTT_F0,TTT_V0)
taxon_names_19 = TTT_19[,1]
write.csv(taxon_names_19,"AT_标志物1.csv")
row.names(TTT_19) <- TTT_19[,1]
TTT_19 <- TTT_19[,-1]
TTT_19_00 = TTT_19[,c(1,2)]
m = t(TTT_19_00)

annotation_col = data.frame(Kingdom=factor(c(rep("Archaea",2),rep("Bacteria",8),rep("Fungi",3),rep("Viruses",1))))
row.names(annotation_col) = colnames(m)
ann_colors <- list(
  Kingdom = c(Bacteria="#3468BB",Fungi="#FFCE19",Archaea="#4AB312",Viruses="#FE0200")
)
p1 <- pheatmap(mat = m,cluster_cols = F,cluster_rows = F,cellwidth = 15,cellheight = 20
         ,show_colnames = T,display_numbers=T,number_format="%.0f",
         annotation_col = annotation_col,border_color = NA,annotation_colors = ann_colors)
################################################################################################
# ROC曲线
# 19个微生物
A_final_data = rbind(A_final_B,A_final_A,A_final_F,A_final_V)
T_final_data = rbind(T_final_B,T_final_A,T_final_F,T_final_V)
A_final_data[A_final_data > 0] <- 1
T_final_data[T_final_data > 0] <- 1
data1 <- A_final_data
data2 <- T_final_data
data1 <- t(data1)
table11 <- data.frame(data1)
table11$type <- "A"
data2 <- t(data2)
table22 <- data.frame(data2)
table22$type <- "T"
AT_final_table <- rbind(table11,table22)
################################################################################################
# 随机森林
auc19 <- rfcv_auc(AT_final_table)
confusion_matrix11 <- confusionMatrix(as.factor(auc19$pred),as.factor(auc19$label))
confusion_matrix11$table
confusion_matrix11$overall[1]
# 19个微生物acc为0.8951613 /16 0.8870968 /14 0.8790323 
roc_prob19 <- roc(auc19$label,auc19$prob,ci=T)
roc_prob19$auc
# 19个微生物auc为0.9555 /16  0.9554 /14 0.9571
################################################################################################
# A_T_protein
# 3454个蛋白
protein_data_all <- read.xlsx("TA3453_AdvanceEarly1104(1).xlsx", sheet = 1)
data_A_T_protein <- protein_data_all[,-c(1,3,4,5,6,7,8,9,10)]
data_A_T_protein <- data_A_T_protein[,1:125]
# 归一化
row.names(data_A_T_protein) <- data_A_T_protein[,1]
data_A_T_protein <- data_A_T_protein[,-1]
means <- apply(data_A_T_protein, 1, mean)
data_A_T_protein <- cbind(data_A_T_protein,ifelse(data_A_T_protein > means, 1, 0)) 
# 格式与菌的数据对齐，先A再T
data_A_T_protein <- data_A_T_protein[,-c(1:124)]
data_A_T_protein <- cbind(data_A_T_protein,data_A_T_protein[1:62])
data_A_T_protein <- data_A_T_protein[,-c(1:62)]
# 蛋白的是按数字大小排的，菌的是按字符串排的
data_A_T_protein <- select(data_A_T_protein, order(colnames(data_A_T_protein)))
# 全部蛋白
table_A_T_protein <- data.frame(t(data_A_T_protein))
row <- substring(row.names(table_A_T_protein),1,1)
table_A_T_protein$type <- row
# 随机森林
model <- rfcv_auc(table_A_T_protein)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.8870968
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.93
table_A_T_protein$type = factor(table_A_T_protein$type,levels = c("A","T"))
set.seed(1234)
AT_rf_model_total_protein <- randomForest(type~., data=table_A_T_protein, ntree=1000, importance=TRUE,proximity=TRUE)
impAT_total_protein = as.data.frame(AT_rf_model_total_protein$importance)
impAT_total_protein = dplyr::arrange(impAT_total_protein,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
index_protein = topgini_index(impAT_total_protein,table_A_T_protein,20)
change_protein = gini_change(table_A_T_protein,index_protein)
change_plot(change_protein)
############################################################
# 菌与蛋白互作
# 先找菌
combined_data <- read.csv('combined_data.csv', sep = ",")
t = c()
j = 1
for (i in 1:nrow(combined_data)){
  if(combined_data[i,]$taxa %in% taxon_names_19){
    t[j] = i
    j = j+1
  }
}
# AT_pairs里包含了菌和蛋白基因名的配对
AT_pairs = combined_data[t,]
AT_pairs = AT_pairs[, c(2,4)]
# 找所有的基因名对应的group名
all_gene_names = unique(AT_pairs[,1])
t1 = c()
j = 1
for (i in 1:nrow(protein_data_all)){
  if(protein_data_all[i,]$PG.Genes %in% all_gene_names){
    t1[j] = i
    j = j+1
  }
}
group_names <- protein_data_all[t1,]$PG.ProteinGroups
# 选取group名在前10的
AT_protein_10_names <- row.names(impAT_total_protein)[1:15]
AT_protein_10_names <- gsub("\\.", ";", AT_protein_10_names)
t2 = c()
j = 1
for (i in 1:length(AT_protein_10_names)){
  if(AT_protein_10_names[i] %in% group_names){
    t2[j] = i
    j = j+1
  }
}
AT_protein_8_names <- AT_protein_10_names[t2]
# 在原始数据中的位置
t3 = c()
j = 1
for (i in 1:nrow(protein_data_all)){
  if(protein_data_all[i,]$PG.ProteinGroups %in% AT_protein_8_names){
    t3[j] = i
    j = j+1
  }
}
xxx = protein_data_all[t3,]$PG.Genes
data_A_T_protein_6 <- protein_data_all[t3,-c(1,3,4,5,6,7,8,9,10)]
data_A_T_protein_6 <- data_A_T_protein_6[,1:125]
# 归一化
row.names(data_A_T_protein_6) <- data_A_T_protein_6[,1]
data_A_T_protein_6 <- data_A_T_protein_6[,-c(1)]
means <- apply(data_A_T_protein_6, 1, mean)
data_A_T_protein_6 <- cbind(data_A_T_protein_6,ifelse(data_A_T_protein_6 > means, 1, 0)) 
# 格式与菌的数据对齐，先A再T
data_A_T_protein_6 <- data_A_T_protein_6[,-c(1:124)]
data_A_T_protein_6 <- cbind(data_A_T_protein_6,data_A_T_protein_6[1:62])
data_A_T_protein_6 <- data_A_T_protein_6[,-c(1:62)]
# 蛋白的是按数字大小排的，菌的是按字符串排的
data_A_T_protein_6 <- select(data_A_T_protein_6, order(colnames(data_A_T_protein_6)))
# 6个蛋白
# 全部蛋白
table_A_T_protein_6 <- data.frame(t(data_A_T_protein_6))
row <- substring(row.names(table_A_T_protein_6),1,1)
table_A_T_protein_6$type <- row
# 随机森林
model <- rfcv_auc(table_A_T_protein_6)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.8629032
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.9251
###########################################################################################
# AT合并
# 18个菌final_data
auc1 <- rfcv_auc(AT_final_table)
confusion_matrix1 <- confusionMatrix(as.factor(auc1$pred),as.factor(auc1$label))
confusion_matrix1$table
confusion_matrix1$overall[1]
# acc为0.8790323 
roc_prob1 <- roc(auc1$label,auc1$prob,ci=T)
roc_prob1
roc_prob1$auc
# auc为0.9571
##################################################
# 8个蛋白
auc2 <- rfcv_auc(table_A_T_protein_6)
confusion_matrix2 <- confusionMatrix(as.factor(auc2$pred),as.factor(auc2$label))
confusion_matrix2$table
confusion_matrix2$overall[1]
# acc为0.8629032 
roc_prob2 <- roc(auc2$label,auc2$prob,ci=T)
roc_prob2
roc_prob2$auc
# auc为0.9251
##################################################
# 27个标志物data_AT_27
data_AT_27_table <- cbind(AT_final_table,table_A_T_protein_6)
data_AT_27_table <- data_AT_27_table[,-c(ncol(data_AT_27_table))]
auc3 <- rfcv_auc(data_AT_27_table)
confusion_matrix3 <- confusionMatrix(as.factor(auc3$pred),as.factor(auc3$label))
confusion_matrix3$table
confusion_matrix3$overall[1]
# acc为0.9354839 
roc_prob3 <- roc(auc3$label,auc3$prob,ci=T)
roc_prob3
roc_prob3$auc
# auc为0.9623
##################################################
# 随机对照
set.seed(123)
random_list <- sample(c(1, 2), 124, replace = TRUE)
random_numbers <- ifelse(random_list == 2, runif(length(random_list), 0, 0.5), runif(length(random_list), 0.5, 1))
roc_prob4 <- roc(auc1$label,random_numbers,ci=T)
roc_prob4$auc
# auc为0.5877
res1 <- roc.test(roc_prob1,roc_prob3)
res1
#p-value = 0.6787
#p-value = 0.0157
res2 <- roc.test(roc_prob2,roc_prob3)
res2
#p-value = 0.00997
#p-value = 0.02548
##################################################
# 合并roc曲线
# font=4
g <- ggroc(list(Microbes=roc_prob1, Protein=roc_prob2, Combination=roc_prob3), size = 3) + 
  annotate("text",x=0.15,y=0.22,label=paste("(AUC = ", round(roc_prob3$auc,3),")"),cex = 5)+
  annotate("text",x=0.15,y=0.25,label=paste("(AUC = ", round(roc_prob2$auc,3),")"),cex = 5)+
  annotate("text",x=0.15,y=0.28,label=paste("(AUC = ", round(roc_prob1$auc,3),")"),cex = 5)
g
g + theme_minimal() + geom_segment(aes(x=1,xend=0,y=0,yend=1),linetype=5,color = "black") + 
  theme(panel.grid = element_blank(),panel.border = element_rect(color = "black", fill = NA)) + 
  coord_fixed(ratio = 1) +
  theme(legend.title = element_blank(),legend.position = c(0.6,0.28),legend.text = element_text(size =  15)) 
  # scale_linetype_manual(values=c("twodash", "dotted", "dotted", "dotted"))+
  # scale_size_manual(values=c(3, 5, 5, 5))
################################################################################################
#重新划分data_AT_27_table
my_data <- as.data.frame(data_AT_27_table)
# 2. 保存数据框为CSV文件
write.csv(my_data, file = "data_AT_27_table.csv", row.names = FALSE)
# 设置随机种子，保证结果可复现
set.seed(123)
# 划分数据集为训练集和测试集
data <- read.csv("data_AT_27_table.csv", header = TRUE)
train_index <- createDataPartition(data$type, p = 84/124, list = FALSE)
train_data <- data[train_index, ]
test_data <- data[-train_index, ]
train_data$type = factor(train_data$type,levels = c("A","T"))
test_data$type = factor(test_data$type,levels = c("A","T"))
# 训练随机森林模型
rf_model <- randomForest(type ~ ., data = train_data, ntree = 500)  # 使用500棵树
# 预测训练集
train_pred <- predict(rf_model, train_data)
# 预测测试集
test_pred <- predict(rf_model, test_data)
# 计算训练集准确率
train_acc <- sum(train_pred == train_data$type) / nrow(train_data)
# 计算测试集准确率
test_acc <- sum(test_pred == test_data$type) / nrow(test_data)
# 输出结果
cat("训练集准确率:", round(train_acc, 4), "\n")
#训练集准确率: 1
cat("测试集准确率:", round(test_acc, 4), "\n")
#测试集准确率: 0.975
# 保存测试集为CSV文件
write.csv(test_data, "test_data.csv", row.names = FALSE)
# 保存随机森林模型
saveRDS(rf_model, "rf_model.rds")
################################################################################################
E_taxon_data <- read.csv('diff_stage_Early.txt', sep = "\t")
L_taxon_data <- read.csv('diff_stage_Advanced.txt', sep = "\t")
# 名称和种类
E_taxon_data_type <- E_taxon_data[,1:2]
L_taxon_data_type <- L_taxon_data[,1:2]
# 全数据表格
row.names(E_taxon_data) <- E_taxon_data[,2]
row.names(L_taxon_data) <- L_taxon_data[,2]
E_taxon_data <- E_taxon_data[,-c(1,2)]
L_taxon_data <- L_taxon_data[,-c(1,2)]
# 每个菌的数量
E_taxon_num <- num_not_zero(E_taxon_data)
L_taxon_num <- num_not_zero(L_taxon_data)
# 合并成一个数目列表
EL_taxon_num <- data.frame(row.names(E_taxon_data))
EL_taxon_num$E <- E_taxon_num$data_0
EL_taxon_num$L <- L_taxon_num$data_0
EL_taxon_num$n <- EL_taxon_num$E+EL_taxon_num$L
# 加上标志物分类
EL_taxon_num$type <- E_taxon_data_type$D
# 两类标准物Bacteria,Fungi的数目
EL_n_Bacteria <- num(EL_taxon_num,"Bacteria")
EL_n_Fungi <- num(EL_taxon_num,"Fungi")
# 对数目列表切分
# 卡一下recurrence,输入参数n,先卡一个大于等于1
EL_taxon_num_Bacteria <- segment_num(EL_taxon_num,"Bacteria",1)
EL_taxon_num_Fungi <- segment_num(EL_taxon_num,"Fungi",1)
# 对数据列表切分
E_taxon_data_Bacteria <- segment_data(E_taxon_data,EL_taxon_num_Bacteria)
L_taxon_data_Bacteria <- segment_data(L_taxon_data,EL_taxon_num_Bacteria)
E_taxon_data_Fungi <- segment_data(E_taxon_data,EL_taxon_num_Fungi)
L_taxon_data_Fungi <- segment_data(L_taxon_data,EL_taxon_num_Fungi)
############################################################
# Bacteria
E_taxon_table_Bacteria <- data.frame(t(E_taxon_data_Bacteria))
E_taxon_table_Bacteria$type <- "A"
L_taxon_table_Bacteria <- data.frame(t(L_taxon_data_Bacteria))
L_taxon_table_Bacteria$type <- "T"
EL_taxon_table_Bacteria <- rbind(E_taxon_table_Bacteria,L_taxon_table_Bacteria)
# 随机森林
model <- rfcv_auc(EL_taxon_table_Bacteria)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.6612903 
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.7304
# 找到最小集合
EL_taxon_table_Bacteria$type = factor(EL_taxon_table_Bacteria$type,levels = c("A","T"))
set.seed(1234)
EL_rf_model_Bacteria <- randomForest(type~., data=EL_taxon_table_Bacteria, ntree=1000, importance=TRUE,proximity=TRUE)
impEL_Bacteria = as.data.frame(EL_rf_model_Bacteria$importance)
impEL_Bacteria = dplyr::arrange(impEL_Bacteria,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
EL_index_Bacteria = topgini_index(impEL_Bacteria,EL_taxon_table_Bacteria,19)
EL_change_Bacteria = gini_change(EL_taxon_table_Bacteria,EL_index_Bacteria)
change_plot(EL_change_Bacteria)
E_final_B <- E_taxon_data_Bacteria[EL_index_Bacteria[1:6],]
L_final_B <- L_taxon_data_Bacteria[EL_index_Bacteria[1:6],]
############################################################
# Fungi
E_taxon_table_Fungi <- data.frame(t(E_taxon_data_Fungi))
E_taxon_table_Fungi$type <- "A"
L_taxon_table_Fungi <- data.frame(t(L_taxon_data_Fungi))
L_taxon_table_Fungi$type <- "T"
EL_taxon_table_Fungi <- rbind(E_taxon_table_Fungi,L_taxon_table_Fungi)
# 随机森林
model <- rfcv_auc(EL_taxon_table_Fungi)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.5322581 
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.6196
# 找到最小集合
EL_taxon_table_Fungi$type = factor(EL_taxon_table_Fungi$type,levels = c("A","T"))
set.seed(1234)
EL_rf_model_Fungi <- randomForest(type~., data=EL_taxon_table_Fungi, ntree=500, importance=TRUE,proximity=TRUE)
impEL_Fungi = as.data.frame(EL_rf_model_Fungi$importance)
impEL_Fungi = dplyr::arrange(impEL_Fungi,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
EL_index_Fungi = topgini_index(impEL_Fungi,EL_taxon_table_Fungi,2)
EL_change_Fungi = gini_change(EL_taxon_table_Fungi,EL_index_Fungi)
change_plot(EL_change_Fungi)
E_final_F <- E_taxon_data_Fungi[EL_index_Fungi[1:2],]
L_final_F <- L_taxon_data_Fungi[EL_index_Fungi[1:2],]
############################################################
################################################################################################
# 热图
t <- c()
for(i in 1:6){
  for(j in 1:19){
    if(row.names(E_taxon_data_Bacteria)[j]==row.names(E_final_B)[i]){
      t[i] = j
    }
  }
}
TTT_B0 <- EL_taxon_num_Bacteria[t,]
t <- c()
for(i in 1:2){
  for(j in 1:2){
    if(row.names(E_taxon_data_Fungi)[j]==row.names(E_final_F)[i]){
      t[i] = j
    }
  }
}
TTT_F0 <- EL_taxon_num_Fungi[t,]
TTT_8 = rbind(TTT_B0,TTT_F0)
TTT_8[4,1] = "Clostridium scindens"
colnames(TTT_8)[2] = "Early"
colnames(TTT_8)[3] = "Advanced"
taxon_names_8 = TTT_8[,1]
row.names(TTT_8) <- TTT_8[,1]
TTT_8 <- TTT_8[,-1]
TTT_8_00 = TTT_8[,c(1,2)]
n = t(TTT_8_00)
annotation_col = data.frame(Kingdom=factor(c(rep("Bacteria",6),rep("Fungi",2))))
row.names(annotation_col) = colnames(n)
ann_colors <- list(
  Kingdom = c(Bacteria="#3468BB",Fungi="#FFCE19")
)
library(pheatmap)
p2 <- pheatmap(mat = n,cluster_cols = F,cluster_rows = F,cellwidth = 15,cellheight = 20
         ,show_colnames = T,display_numbers=T,number_format="%.0f",
         annotation_col = annotation_col,border_color = NA,annotation_colors = ann_colors)
library(RColorBrewer)
Colormap <- colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100)
breaks <- seq(min(unlist(c(m, n))), max(unlist(c(m, n))), length.out=100)
pheatmap(mat = m,color=Colormap,breaks=breaks,cluster_cols = F,cluster_rows = F,cellwidth = 15,cellheight = 20
         ,show_colnames = T,display_numbers=T,number_format="%.0f",
         annotation_col = annotation_col,border_color = NA,annotation_colors = ann_colors)
pheatmap(mat = n,color=Colormap,breaks=breaks,cluster_cols = F,cluster_rows = F,cellwidth = 15,cellheight = 20
         ,show_colnames = T,display_numbers=T,number_format="%.0f",
         annotation_col = annotation_col,border_color = NA,annotation_colors = ann_colors)
################################################################################################
# ROC曲线
E_final_data = rbind(E_final_B,E_final_F)
L_final_data = rbind(L_final_B,L_final_F)
E_final_data[E_final_data > 0] <- 1
L_final_data[L_final_data > 0] <- 1
data1 <- E_final_data
data2 <- L_final_data
data1 <- t(data1)
table11 <- data.frame(data1)
table11$type <- "A"
data2 <- t(data2)
table22 <- data.frame(data2)
table22$type <- "T"
EL_final_table <- rbind(table11,table22)
# 随机森林
# 8个微生物EL_final_table
auc8 <- rfcv_auc(EL_final_table)
confusion_matrix11 <- confusionMatrix(as.factor(auc8$pred),as.factor(auc8$label))
confusion_matrix11$table
confusion_matrix11$overall[1]
# 8个微生物acc为0.6451613 
roc_prob8 <- roc(auc8$label,auc8$prob,ci=T)
roc_prob8$auc
# 8个微生物auc为0.7429
################################################################################################
# E_L_protein
# 1014个蛋白
protein_data_all <- read.xlsx("TA3453_AdvanceEarly1104(1).xlsx", sheet = 2)
data_E_L_protein <- protein_data_all[,-c(1,3,4,5,6,7,8)]
data_E_L_protein[1,1] <- "type"
y1 = data_E_L_protein[,1]
data_E_L_protein <- data_E_L_protein[,-1]
x1 = data_E_L_protein[1,]
data_E_L_protein <- data_E_L_protein[-1,]
data_E_L_protein <- data.frame(data_E_L_protein)
data_E_L_protein <- apply(data_E_L_protein, 2, as.numeric)
means <- apply(data_E_L_protein, 1, mean)
data_E_L_protein <- cbind(data_E_L_protein,ifelse(data_E_L_protein > means, 1, 0)) 
data_E_L_protein <- data_E_L_protein[,-c(1:62)]
data_E_L_protein <- rbind(x1,data_E_L_protein)
data_E_L_protein <- cbind(y1,data_E_L_protein)
data_E_L_protein[data_E_L_protein == "Early_stage"] <- "A"
data_E_L_protein[data_E_L_protein == "Advanced_stage"] <- "T"
row.names(data_E_L_protein) <- data_E_L_protein[,1]
data_E_L_protein <- data_E_L_protein[,-1]
table_E_L_protein <- data.frame(t(data_E_L_protein))

# 随机森林
model <- rfcv_auc(table_E_L_protein)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.6774194
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.7654
table_E_L_protein$type = factor(table_E_L_protein$type,levels = c("A","T"))
set.seed(1234)
EL_rf_model_total_protein <- randomForest(type~., data=table_E_L_protein, ntree=1000, importance=TRUE,proximity=TRUE)
impEL_total_protein = as.data.frame(EL_rf_model_total_protein$importance)
impEL_total_protein = dplyr::arrange(impEL_total_protein,desc(MeanDecreaseGini))
# 获取重要度排名靠前的变量索引
index_protein = topgini_index(impEL_total_protein,table_E_L_protein,20)
change_protein = gini_change(table_E_L_protein,index_protein)
change_plot(change_protein)
############################################################
# 菌与蛋白互作
# 先找菌
combined_data <- read.csv('combined_data.csv', sep = ",")
t = c()
j = 1
for (i in 1:nrow(combined_data)){
  if(combined_data[i,]$taxa %in% taxon_names_8){
    t[j] = i
    j = j+1
  }
}
# AT_pairs里包含了菌和蛋白基因名的配对
EL_pairs = combined_data[t,]
EL_pairs = EL_pairs[, c(2,4)]
# 找所有的基因名对应的group名
all_gene_names = unique(EL_pairs[,1])
t1 = c()
j = 1
for (i in 1:nrow(protein_data_all)){
  if(protein_data_all[i,]$PG.Genes %in% all_gene_names){
    t1[j] = i
    j = j+1
  }
}
group_names <- protein_data_all[t1,]$PG.ProteinGroups
q = data.frame(group_names)
# 选取group名在前10的
EL_protein_10_names <- row.names(impEL_total_protein)[1:12]
EL_protein_10_names <- gsub("\\.", ";", EL_protein_10_names)
t2 = c()
j = 1
for (i in 1:15){
  if(EL_protein_10_names[i] %in% group_names){
    t2[j] = i
    j = j+1
  }
}
EL_protein_8_names <- EL_protein_10_names[t2]
# 在原始数据中的位置
t3 = c()
j = 1
for (i in 1:nrow(protein_data_all)){
  if(protein_data_all[i,]$PG.ProteinGroups %in% EL_protein_8_names){
    t3[j] = i
    j = j+1
  }
}
xxx = protein_data_all[t3,]$PG.Genes

data_E_L_protein_6 <- protein_data_all[t3,-c(1,3,4,5,6,7,8)]
y11 = data_E_L_protein_6[,1]
data_E_L_protein_6 <- data_E_L_protein_6[,-1]
# 归一化
data_E_L_protein_6 <- data.frame(data_E_L_protein_6)
data_E_L_protein_6 <- apply(data_E_L_protein_6, 2, as.numeric)
means <- apply(data_E_L_protein_6, 1, mean)
data_E_L_protein_6 <- cbind(data_E_L_protein_6,ifelse(data_E_L_protein_6 > means, 1, 0)) 
data_E_L_protein_6 <- data_E_L_protein_6[,-c(1:62)]
data_E_L_protein_6 = rbind(x1,data_E_L_protein_6)
y11 = c("type",y11)
data_E_L_protein_6 <- cbind(y11,data_E_L_protein_6)
data_E_L_protein_6[data_E_L_protein_6 == "Early_stage"] <- "A"
data_E_L_protein_6[data_E_L_protein_6 == "Advanced_stage"] <- "T"
row.names(data_E_L_protein_6) <- data_E_L_protein_6[,1]
data_E_L_protein_6 <- data_E_L_protein_6[,-1]
table_E_L_protein_6 <- data.frame(t(data_E_L_protein_6))

# 随机森林
model <- rfcv_auc(table_E_L_protein_6)
confusion_matrix <- confusionMatrix(as.factor(model$pred),as.factor(model$label))
confusion_matrix$table
confusion_matrix$overall[1]
# acc为0.7580645
roc_prob <- roc(model$label,model$prob,ci=T)
roc_prob$auc
# auc为0.8767
###########################################################################################
# EL合并
# 18个菌final_data
EL_final_data = cbind(E_final_data,L_final_data)
EL_final_data = rbind(c(rep("A",33),rep("T",29)),EL_final_data)
row.names(EL_final_data)[1] = "type"
EL_final_data <- select(EL_final_data, order(colnames(EL_final_data)))
tableEL <- data.frame(t(EL_final_data))

auc1 <- rfcv_auc(tableEL)
confusion_matrix1 <- confusionMatrix(as.factor(auc1$pred),as.factor(auc1$label))
confusion_matrix1$table
confusion_matrix1$overall[1]
# acc为0.7096774 
roc_prob1 <- roc(auc1$label,auc1$prob,ci=T)
roc_prob1
roc_prob1$auc
# auc为0.7915
##################################################
# 8个蛋白
data_E_L_protein_6 <- select(data_E_L_protein_6, order(colnames(data_E_L_protein_6)))
tableEL_P = data.frame(t(data_E_L_protein_6))
auc2 <- rfcv_auc(tableEL_P)
confusion_matrix2 <- confusionMatrix(as.factor(auc2$pred),as.factor(auc2$label))
confusion_matrix2$table
confusion_matrix2$overall[1]
# acc为0.7580645
roc_prob2 <- roc(auc2$label,auc2$prob,ci=T)
roc_prob2
roc_prob2$auc
# auc为0.8689
##################################################
# 27个标志物data_AT_27
data_EL_27_table <- cbind(tableEL,tableEL_P)
data_EL_27_table <- data_EL_27_table[,-c(1)]
auc3 <- rfcv_auc(data_EL_27_table)
confusion_matrix3 <- confusionMatrix(as.factor(auc3$pred),as.factor(auc3$label))
confusion_matrix3$table
confusion_matrix3$overall[1]
# acc为0.8387097
roc_prob3 <- roc(auc3$label,auc3$prob,ci=T)
roc_prob3
roc_prob3$auc
# auc为0.9263
##################################################
# 随机对照
set.seed(123)
random_list <- sample(c(1, 2), 124, replace = TRUE)
random_numbers <- ifelse(random_list == 2, runif(length(random_list), 0, 0.5), runif(length(random_list), 0.5, 1))
roc_prob4 <- roc(auc1$label,random_numbers,ci=T)
roc_prob4$auc
# auc为0.5877
##################################################
# 合并roc曲线
g <- ggroc(list(Microbes=roc_prob1, Protein=roc_prob2, Combination=roc_prob3), size = 3) + 
  annotate("text",x=0.15,y=0.22,label=paste("(AUC = ", round(roc_prob3$auc,3),")"),cex = 5)+
  annotate("text",x=0.15,y=0.25,label=paste("(AUC = ", round(roc_prob2$auc,3),")"),cex = 5)+
  annotate("text",x=0.15,y=0.28,label=paste("(AUC = ", round(roc_prob1$auc,3),")"),cex = 5)
g
g + theme_minimal() + geom_segment(aes(x=1,xend=0,y=0,yend=1),linetype=5,color = "black",size = 2) + 
  theme(panel.grid = element_blank(),panel.border = element_rect(color = "black", fill = NA,size = 2)) + 
  coord_fixed(ratio = 1) + theme(axis.text = element_text( size = 15))+
  theme(legend.title = element_blank(),legend.position = c(0.6,0.28),legend.text = element_text(size =  15)) 
################################################################################################
################################################################################################
```

#run_pheatmap_clusterRow
args=commandArgs(TRUE)
inf1=args[1]
inf2=args[2]
outf=args[3]
outf_order=args[4]
library(pheatmap)
data=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=1)
data=as.data.frame(t(data))

group=read.table(inf2,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F)
rownames(group)=group[,1]
data=data[,colnames(data) %in% rownames(group)]
group=group[colnames(data),]
group1=group
group1=rbind(group1[group1[,2]=="Immune cells",],group1[group1[,2]=="Bacteria",],group1[group1[,2]=="Archaea",],group1[group1[,2]=="Viruses",])
group1=as.data.frame(group1[,-1])
rownames(group1)=rownames(group)
colnames(group1)<-"Groups"

data1=data[,rownames(group1)]
aa<-pheatmap(as.matrix(data1),clustering_method="ward.D2",annotation_col=group1,cluster_rows=T,cluster_cols=F,treeheight_col=50,fontsize_row=5,fontsize_col=1,filename = outf)
order_row<-aa$tree_row$order
sampleName<-rownames(data)
sampleOrder<-as.data.frame(sampleName[order_row])
write.table(sampleOrder,outf_order,sep = "\t",quote=F,row.names=FALSE,col.names=FALSE)

#run_pheatmap_order_clusterCol
args=commandArgs(TRUE)
inf1=args[1]
inf2=args[2]
outf=args[3]
outf_order=args[4]
library(pheatmap)
data=read.table(inf1,sep="\t",quote="",header=T,stringsAsFactors=F,check.names=F,row.names=1)
data=as.data.frame(t(data))
group=read.table(inf2,sep="\t",quote="",header=F,stringsAsFactors=F,check.names=F)
data1=data[group[,1],]
aa<-pheatmap(as.matrix(data1),cluster_rows=F,cluster_cols=T,treeheight_col=50,fontsize_row=6,fontsize_col=6,filename = outf)
order_col<-aa$tree_col$order
sampleName<-colnames(data)
sampleOrder<-as.data.frame(sampleName[order_col])
write.table(sampleOrder,outf_order,sep = "\t",quote=F,row.names=FALSE,col.names=FALSE)

